#!/bin/bash

make
# find all directories that start with test
for d in test*/; do
  #find all .bin files
  for f in $d*.bin; do
    echo testing $f
    # diff them with the .out file
    ./12bit $f | diff - ${f:0:${#f}-3}out
    # if exit code not 0 there was a diff
    if [ $? != 0 ]; then 
      echo $f failed!
      # keep a count of failures
      let fail+=1
    fi
    let total+=1
  done
done  
# values default to 0 so these work fine.
let 'pass = total-fail'
echo $pass of $total tests passed!
